# Generated by Django 6.1.1 on 2026-10-08 16:53

from django.db import migrations, models


def keep_one_owner_per_group(apps, schema_editor):
    Membership = apps.get_model('finance', 'GroupMembership')
    seen_groups = set()
    demote_ids = []
    owners = Membership.objects.filter(role='OWNER').order_by(
        'group_id', 'created_at', 'pk',
    ).values_list('pk', 'group_id')
    for membership_id, group_id in owners.iterator():
        if group_id in seen_groups:
            demote_ids.append(membership_id)
        else:
            seen_groups.add(group_id)
    if demote_ids:
        Membership.objects.filter(pk__in=demote_ids).update(role='MEMBER')


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_category_user'),
    ]

    operations = [
        migrations.RunPython(keep_one_owner_per_group, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'OWNER')), fields=('group',), name='unique_group_owner'),
        ),
    ]
